site_name: Cloudmesh AI CMC
repo_url: https://github.com/cloudmesh-ai/cloudmesh-ai-cmc
repo_name: cloudmesh-ai-cmc

theme:
  name: material

docs_dir: docs
use_directory_urls: false

nav:
  - Home: index.md
  - User Guide:
      - CLI Reference: cli.md
      - Telemetry: telemetry.md
      - Troubleshooting: troubleshooting.md
  - Developer Guide:
      - Creating Extensions: extensions.md
      - Architecture: architecture.md
  - Project:
      - Changelog: ../CHANGELOG.md
      - GitHub: https://github.com/cloudmesh-ai/cloudmesh-ai-cmc
      - Issues: https://github.com/cloudmesh-ai/cloudmesh-ai-cmc/issues
  - API Reference: api.md

plugins:
  - cloudmesh-ai-theme
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_section_style: table
            docstring_style: google
            group_by_category: true
            members: true
            separate_signature: true
            show_category_heading: true
            show_root_full_path: true
            show_source: true
            show_submodules: true
          paths:
            - src

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
      line_spans: __span
      pygments_style: colorful
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed
  - admonition
  - pymdownx.details