import click
import os
import re


@click.command(name="gemini")
@click.argument("filename", type=click.Path(exists=True))
def gemini_fix(filename):
    """
    Clean and standardize Gemini-generated Markdown files.

    This command performs surgical cleanup on Markdown files generated by Gemini AI
    to ensure they are compatible with standard Markdown renderers and documentation
    generators (like MkDocs or Quarto).

    Key transformations:
    1. Snaps 'Bash ```' labels to the left margin and converts them to '```bash'.
    2. Ensures the first non-empty line is a proper H1 header (# Title).
    3. Removes leading indentation from code block fences to prevent nested blocks.
    4. Detects 'naked' shell commands (e.g., sudo, apt, pip) and automatically
       wraps them in bash code blocks.

    Examples:
        cme markdown fix gemini guide.md
        cme markdown fix gemini README.md
    """
    try:
        with open(filename, "r", encoding="utf-8") as f:
            content = f.read()

        if not content:
            click.echo("File is empty.")
            return

        # 1. HYBRID SURGICAL REPLACE
        # Match any leading space, the word 'Bash', any whitespace, and the ticks.
        pattern = r"(?i)^\s*Bash\s+```"
        content = re.sub(pattern, r"```bash", content, flags=re.MULTILINE)

        lines = content.splitlines()
        new_lines = []
        header_fixed = False
        in_code_block = False

        # Patterns for naked commands
        bash_patterns = (
            r"^(sudo|apt|pip|python|mkdir|cd|ls|git|echo|npm|docker|chmod|make)\s"
        )

        for line in lines:
            stripped = line.strip()

            # A. Enforce H1 on first content
            if not header_fixed and stripped:
                clean_text = stripped.lstrip("#").strip()
                new_lines.append(f"# {clean_text}")
                header_fixed = True
                continue

            # B. Track Code Block State
            if stripped.startswith("```"):
                in_code_block = not in_code_block
                new_lines.append(stripped)
                continue

            # C. Wrap Naked Commands
            if not in_code_block and re.match(bash_patterns, stripped):
                new_lines.append("```bash")
                new_lines.append(stripped)
                new_lines.append("```")
            else:
                new_lines.append(line)

        # Write to disk
        with open(filename, "w", encoding="utf-8") as f:
            f.write("\n".join(new_lines) + "\n")

        click.secho(
            f"SUCCESS: {os.path.basename(filename)} has been updated.", fg="green"
        )

    except Exception as e:
        click.secho(f"ERROR: Formatting failed: {e}", fg="red")


def register(group):
    """Registers the gemini command to the 'fix' group."""
    group.add_command(gemini_fix)
